# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoboletas',
            name='conver',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ingresoboletas',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingresoboletas',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='ingresoboletas',
            name='impresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingresoboletas',
            name='numeroboleta',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingresoboletas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
