# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0002_auto_20160831_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingresoboletas',
            new_name='ingresoboleta',
        ),
    ]
