# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0003_auto_20160831_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoboleta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
