# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0004_auto_20160831_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoboleta',
            old_name='numeroboleta',
            new_name='numerodeboleta',
        ),
    ]
