# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0005_auto_20160831_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoboleta',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
