# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0006_auto_20160831_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoboleta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingresoboleta',
            name='codigo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingresoboleta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingresoboleta',
            name='precio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingresoboleta',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresoboleta',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresoboleta',
            name='vendedor',
            field=models.IntegerField(default=1),
        ),
    ]
